// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpBZpsg_ek8WrUk06-rPzz8YyZJgtSiLI',
    appId: '1:446732876688:web:641dac0c4add38a2501115',
    messagingSenderId: '446732876688',
    projectId: 'apkcadastroproduto',
    authDomain: 'apkcadastroproduto.firebaseapp.com',
    storageBucket: 'apkcadastroproduto.appspot.com',
    measurementId: 'G-Q0QT5RBPNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0E7i1pXhwlqbnV0WwK4gIIjd3vlrgCNI',
    appId: '1:446732876688:android:14e0c93b8795cd10501115',
    messagingSenderId: '446732876688',
    projectId: 'apkcadastroproduto',
    storageBucket: 'apkcadastroproduto.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpBZpsg_ek8WrUk06-rPzz8YyZJgtSiLI',
    appId: '1:446732876688:web:7bbd60636d51e89d501115',
    messagingSenderId: '446732876688',
    projectId: 'apkcadastroproduto',
    authDomain: 'apkcadastroproduto.firebaseapp.com',
    storageBucket: 'apkcadastroproduto.appspot.com',
    measurementId: 'G-FB078HFRZV',
  );
}
